config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :tournaments do
    resources :tournament_members
  end
  
  resources :teams do
    resources :team_members
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  # before_create :set_cap

  belongs_to :user
  belongs_to :team

  validates_uniqueness_of :user, scope: :team, presence: true

  enum role: [:member, :owner]

end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update]

  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.where(team_id: params[:team_id])
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)
    @team_member.user_id = current_user.id

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to team_team_members_path, notice: 'You joined the team' }
        format.json { render :index, status: :created, location: @team_member }
      else
        format.html { redirect_to team_team_members_path, alert: 'User already exist' }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    team_member = TeamMember.find_by(team_id: params[:team_id], user_id: params[:id])
    team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_team_members_path, notice: 'You leave the team' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find_by(team_id: params[:team_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.permit(:role, :team_id, :user_id, :id)
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.haml
= form_for(team_team_members_path) do |f|
  .field
    = f.label :role
    = f.number_field :role
  .field
    = f.label :team_id
    = f.number_field :team_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit

app/views/team_members/edit.html.haml
%h1 Editing Team Member
= render 'form', team_member: @team_member
= link_to 'Show', @team_member
|
= link_to 'Back', team_members_path

app/views/team_members/index.html.haml
.container
  %h2 Team Members
  -if user_signed_in?
    - if @team_members.any? { |a| a.user == current_user}
      = link_to 'Leave team', team_team_member_path(id: current_user.id), method: :delete, class: 'btn btn-success'
    - else
      = link_to 'Join team', team_team_members_path, action: :create, method: :post, class: 'btn btn-success'

  %table.table.table-hover
    %thead
      %tr
        %th Role
        %th User
    %tbody
      - @team_members.each do |team_member|
        %tr
          %td= team_member.role
          %td= team_member.user.inspect

app/views/team_members/new.html.haml
%h1 New Team Member
= render 'form', team_member: @team_member
= link_to 'Back', team_team_members_path

app/views/team_members/show.html.haml
%p
  %strong Role:
  = @team_member.role
%p
  %strong Team:
  = @team_member.team_id
%p
  %strong User:
  = @team_member.user_id
= link_to 'Edit', edit_team_member_path(@team_member)
|
= link_to 'Back', team_members_path