config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :tournaments do
    resources :tournament_members
  end
  
  resources :teams do
    resources :team_members
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :tournament_members, dependent: :destroy
  has_many :teams, through: :tournament_members

  validates :name, uniqueness: true, presence: true
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to tournaments_path, notice: 'Tournament was successfully created.' }
        format.json { render :index, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :team_id, :tournament_id)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.haml
= simple_form_for tournament do |f|
  = f.input :name
  .form-group
    = f.button :submit, class: 'btn btn-success'

app/views/tournaments/destroy.js.erb
$('.delete_staff').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
});

app/views/tournaments/edit.html.haml
.container
  %h1 Editing Tournament
  = render 'form', tournament: @tournament
  = link_to 'Show', @tournament, class: 'btn btn-info'
  |
  = link_to 'Back', tournaments_path, class: 'btn btn-info'

app/views/tournaments/index.html.haml
.container
  %h2 Tournaments #{link_to 'New Tournament', new_tournament_path, class: 'btn btn-success' if user_signed_in?}
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Registred teams
        %th Playrуs
        %th Status
        %th Menu
    %tbody
      %tbody
        - @tournaments.each do |tournament|
          %tr
            %td= tournament.name
            %td= tournament.tournament_members.count
            %td= link_to 'Participants', tournament_tournament_members_path(tournament), class: 'btn btn-warning'
            %td
              -if user_signed_in?
                -if tournament.teams.any? {|team| team.user_id == current_user.id}
                  = link_to 'Leave', tournament_tournament_member_path(id: TournamentMember.find_by(tournament_id: tournament.id).id, tournament_id: tournament.id), method: :delete, class: 'btn btn-success'
                -else
                  = link_to 'Register', tournament_tournament_members_path(tournament_id: tournament.id, team_id: Team.find_by(owner: current_user)),
                   action: :create, method: :post, class: 'btn btn-success' if TeamMember.owner.any? {|owner| owner.user_id == current_user.id}
            %td
              -if user_signed_in?
                = link_to 'Edit', edit_tournament_path(tournament), class: 'btn btn-primary'
                = link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/tournaments/new.html.haml
.container
  %h2 New Tournament
  = render 'form', tournament: @tournament
  = link_to 'Back', tournaments_path, class: 'btn btn-info'

app/views/tournaments/show.html.haml
%p
  %strong Name:
  = @tournament.name
= link_to 'Edit', edit_tournament_path(@tournament)
|
= link_to 'Back', tournaments_path