config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :tournaments do
    resources :tournament_members
  end
  
  resources :teams do
    resources :team_members
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tournament_member.rb
class TournamentMember < ApplicationRecord

  belongs_to :tournament
  belongs_to :team

  validates_uniqueness_of :team, scope: :tournament, presence: true

end

app/controllers/tournament_members_controller.rb
class TournamentMembersController < ApplicationController
  before_action :set_tournament_member, only: [:show, :edit, :update]

  # GET /tournament_members
  # GET /tournament_members.json
  def index
    @tournament_members = TournamentMember.all
  end

  # GET /tournament_members/1
  # GET /tournament_members/1.json
  def show
  end

  # GET /tournament_members/new
  def new
    @tournament_member = TournamentMember.new
  end

  # GET /tournament_members/1/edit
  def edit
  end

  # POST /tournament_members
  # POST /tournament_members.json
  def create
    @tournament_member = TournamentMember.new(tournament_member_params)
    respond_to do |format|
      if @tournament_member.save
        format.html { redirect_to tournaments_path, notice: 'Tournament member was successfully created.' }
        format.json { render :show, status: :created, location: @tournament_member }
      else
        format.html { redirect_to tournaments_path, alert: 'Already exist' }
        format.json { render json: @tournament_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournament_members/1
  # PATCH/PUT /tournament_members/1.json
  def update
    respond_to do |format|
      if @tournament_member.update(tournament_member_params)
        format.html { redirect_to @tournament_member, notice: 'Tournament member was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament_member }
      else
        format.html { render :edit }
        format.json { render json: @tournament_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournament_members/1
  # DELETE /tournament_members/1.json
  def destroy
    tournament_member = TournamentMember.find_by(id: params[:id], tournament_id: params[:tournament_id])
    tournament_member.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_path, notice: 'Tournament member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament_member
      @tournament_member = TournamentMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_member_params
      params.permit(:team_id, :tournament_id, :id)
    end
end

app/helpers/tournament_members_helper.rb
module TournamentMembersHelper
end

app/views/tournament_members/_form.html.haml
= form_for(tournament_member) do |f|
  .field
    = f.label :team_id
    = f.number_field :team_id
  .field
    = f.label :tournament_id
    = f.number_field :tournament_id
  .actions
    = f.submit

app/views/tournament_members/edit.html.haml
%h1 Editing Tournament Member
= render 'form', tournament_member: @tournament_member
= link_to 'Show', @tournament_member
|
= link_to 'Back', tournament_members_path

app/views/tournament_members/index.html.haml
.container
  %h2 Tournament Members
  %table.table.table-hover
    %thead
      %tr
        %th Avatar
        %th Team name
        %th Captain Nick
        %th Register Time
    %tbody
      - @tournament_members.each do |tournament_member|
        %tr
          %td= image_tag tournament_member.team.image.url(:thumb_200), class:'img_value' if tournament_member.team.image?
          %td= tournament_member.team.name
          %td= tournament_member.team.owner.inspect
          %td= I18n.localize tournament_member.team.created_at, format: :my_time

=@tournament_members.inspect

app/views/tournament_members/new.html.haml
%h1 New Tournament Member
= render 'form', tournament_member: @tournament_member
= link_to 'Back', tournament_members_path

app/views/tournament_members/show.html.haml
%p
  %strong Team:
  = @tournament_member.team_id
%p
  %strong Tournament:
  = @tournament_member.tournament_id
= link_to 'Edit', edit_tournament_member_path(@tournament_member)
|
= link_to 'Back', tournament_members_path