config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  resources :tournaments do
    resources :tournament_members
  end
  
  resources :teams do
    resources :team_members
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home Page', root_path, :class => 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li= link_to 'Teams', teams_path
        %li= link_to 'Tournaments', tournaments_path
        %li= link_to('', '#')
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to('My Account', edit_user_registration_path)
          %li= link_to "Sign out", destroy_user_session_path, :method => :delete
        - else
          %li= link_to('Sign in', new_user_session_path)
          %li= link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Teh
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container
      = flash_message
    = yield